### PR TITLE
[JBTM-3498] Broken links on the narayana.io site

### PR DESCRIPTION
**Pull request by sudeshnas93**
Issue: https://issues.redhat.com/browse/JBTM-3498

### CODE REVIEW

**Comment by ochaloup** [comment]
TESTIT

**Comment by mmusgrov** [comment]
If I download the CI run artifacts and look at file:///home/xx/Downloads/archive/_site/index.html in my browser then the links are still broken. @ochaloup do you know if that is a valid way of checking whether the PR is working or do you think we need rebuild the site first?

**Comment by mmusgrov** [comment]
@sudeshnas93 do you know whether or not the rendering of the RSS feeds works? If you're not sure then I'd suggest you follow Tom's advice and add html links to the forum and blogs instead.

**Comment by ochaloup** [comment]
@mmusgrov `do you know if that is a valid way of checking whether the PR is working` I think downloading the result _site artifacts should be fine for verification.

**Comment by sudeshnas93** [comment]
> @sudeshnas93 do you know whether or not the rendering of the RSS feeds works? If you're not sure then I'd suggest you follow Tom's advice and add html links to the forum and blogs instead.

I am not sure how RSS feed works. So, following @tomjenkinson 's advice. I am sending a PR. Please review.

**Comment by mmusgrov** [comment]
The updates are not rendering very well. You can see how it looks either by downloading the artefacts from the job (http://narayanaci1.eng.hst.ams2.redhat.com/job/btny-pulls-narayanaio/8/artifact/) or by [building the site](https://github.com/jbosstm/narayana.io/blob/develop/README.md) on your laptop and then look at the output in a browser (file:///home/user/Downloads/archive/_site/index.html). If you decide to build the site yourself then the build instructions may need tweaking for your platform.

I think most of the narayana team are quite busy at the moment but if you need help then do let us know.

**Comment by mmusgrov** [comment]
Actually @sudeshnas93 , I notice that our CI run failed which means the generated site output isn't valid.
We do get transient failures in our CI infrastructure so I will trigger another run.

**Comment by mmusgrov** [comment]
TESTIT

**Comment by sudeshnas93** [comment]
> The updates are not rendering very well. You can see how it looks either by downloading the artefacts from the job (http://narayanaci1.eng.hst.ams2.redhat.com/job/btny-pulls-narayanaio/8/artifact/) or by [building the site](https://github.com/jbosstm/narayana.io/blob/develop/README.md) on your laptop and then look at the output in a browser (file:///home/user/Downloads/archive/_site/index.html). If you decide to build the site yourself then the build instructions may need tweaking for your platform.
> 
> I think most of the narayana team are quite busy at the moment but if you need help then do let us know.

Hello @mmusgrov, I have read through CI logs and figured out it was an indentation problem. I am trying to fix it by building it locally. If I need help, I will reach out to you.

**Comment by sudeshnas93** [comment]
Hello,
I have downloaded the artifacts and rendered the index.html. It looks like the links are working perfectly fine. Please review. :)

**Comment by mmusgrov** [comment]
Well figured out @sudeshnas93 
The contribution looks good, thank you for proactively fixing it.
Before merging your work can we just ask you to squash your commits:
```
git rebase -i 55a66baa6
```
keeping the top commit and prefix your commit comment with the JIRA issue number. So `git log -1` should look like the following:
```
[mmusgrov@dev2 narayana.io] ((HEAD detached from pr/40)) $ git log --oneline -1
c6ed2855c (HEAD) [JBTM-3498] Broken links on the narayana.io site
```

**Comment by sudeshnas93** [comment]
> Well figured out @sudeshnas93
> The contribution looks good, thank you for proactively fixing it.
> Before merging your work can we just ask you to squash your commits:
> 
> ```
> git rebase -i 55a66baa6
> ```
> 
> keeping the top commit and prefix your commit comment with the JIRA issue number. So `git log -1` should look like the following:
> 
> ```
> [mmusgrov@dev2 narayana.io] ((HEAD detached from pr/40)) $ git log --oneline -1
> c6ed2855c (HEAD) [JBTM-3498] Broken links on the narayana.io site
> ```

Hi @mmusgrov , I have squashed the commits, and looks great. Thank you :) Please merge it.

**Review by mmusgrov — APPROVED** [review]
Thanks for the contribution

**Pull request merged**
