### PR TITLE
Import from Hugo website

### PR DESCRIPTION
**Pull request by marcosgopen**
Change from Awestruct framework to Hugo

### CODE REVIEW

**Comment by mmusgrov** [comment]
You should include some instructions on how to test site, including which software versions are required.

The PR is missing a `hugo.toml` file so I fetched your PR locally and added that config file and ran `hugo serve` and it still produced a 404 so I installed a theme and added it to `hugo.toml`. That looked more promising and it got further but the site didn't display because of:

```
ERROR render of "page" failed: "/home/mmusgrov/src/forks/narayana/narayana.io/layouts/_default/documentation.html:38:6": execute of template failed: template: _default/documentation.html:38:6: executing "main" at <partial "main/docs-navigation.html" .>: error calling partial: partial "main/docs-navigation.html" not found
```

**Comment by marcosgopen** [comment]
> You should include some instructions on how to test site, including which software versions are required.
> 
> The PR is missing a `hugo.toml` file so I fetched your PR locally and added that config file and ran `hugo serve` and it still produced a 404 so I installed a theme and added it to `hugo.toml`. That looked more promising and it got further but the site didn't display because of:
> 
> ```
> ERROR render of "page" failed: "/home/mmusgrov/src/forks/narayana/narayana.io/layouts/_default/documentation.html:38:6": execute of template failed: template: _default/documentation.html:38:6: executing "main" at <partial "main/docs-navigation.html" .>: error calling partial: partial "main/docs-navigation.html" not found
> ```

I am sorry for that, I tested it in my local environment and that is all what I needed to run the site. I will add more instructions on how to test the site tomorrow (software version required...).

**Comment by marcosgopen** [comment]
@mmusgrov I have updated the website and then I tested it successfully on a fedora docker container:
Could you please retry now?
This is my reproducer and tools'  versions


_[root@0ff24b03a65c narayana.io]# history
    1  ls
    2  cd home
    3  ls
    4  git clone https://github.com/marcosgopen/narayana.io
    5  yum install git
    6  **git clone https://github.com/marcosgopen/narayana.io**
    7  git checkout hugo-website
    8  git branch -a
    9  cd narayana.io/
   10  git branch -a
   11  **git checkout hugo-website**
   12  **dnf install hugo**
   13  npm install
   14  **yum install npm**
   15  **npm install**
   16  **hugo -e development**
   17  **hugo serve**
   18  history
[root@0ff24b03a65c narayana.io]# npm --version
9.6.7  // locally I have npm version 8.13.2 and it works too
[root@0ff24b03a65c narayana.io]# hugo version
hugo v0.101.0+extended linux/amd64 BuildDate=unknown_

**Comment by marcosgopen** [comment]
> You should include some instructions on how to test site, including which software versions are required.
> 
> The PR is missing a `hugo.toml` file so I fetched your PR locally and added that config file and ran `hugo serve` and it still produced a 404 so I installed a theme and added it to `hugo.toml`. That looked more promising and it got further but the site didn't display because of:
> 
> ```
> ERROR render of "page" failed: "/home/mmusgrov/src/forks/narayana/narayana.io/layouts/_default/documentation.html:38:6": execute of template failed: template: _default/documentation.html:38:6: executing "main" at <partial "main/docs-navigation.html" .>: error calling partial: partial "main/docs-navigation.html" not found
> ```

Thank you for your comment, this was my mistake and I fixed it. BTW that error didn't prevent me from deploying the website.

**Comment by marcosgopen** [comment]
> You should include some instructions on how to test site, including which software versions are required.
> 
> The PR is missing a `hugo.toml` file so I fetched your PR locally and added that config file and ran `hugo serve` and it still produced a 404 so I installed a theme and added it to `hugo.toml`. That looked more promising and it got further but the site didn't display because of:
> 
> ```
> ERROR render of "page" failed: "/home/mmusgrov/src/forks/narayana/narayana.io/layouts/_default/documentation.html:38:6": execute of template failed: template: _default/documentation.html:38:6: executing "main" at <partial "main/docs-navigation.html" .>: error calling partial: partial "main/docs-navigation.html" not found
> ```

That is strange Mike because I don't need the hugo.toml to build and deploy the website, I think the theme.toml is sufficient.

**Comment by mmusgrov** [comment]
I need to be able to test your PR directly not your own branch since I am providing a review, here's what I did:

.git/config entry for pulling your PR
[remote "upstream"]
        url = ssh://git@github.com/jbosstm/narayana.io.git
        fetch = +refs/pull/*/head:refs/remotes/pr/*

$ which hugo
/usr/bin/hugo # I also tried it with /var/lib/snapd/snap/bin/hugo

git fetch
git co pr/63
hugo -e development
hugo serve

When I load http://localhost:1313 in my browser hugo genereates an empty page.

Same behaviour when I use your branch directly.

**Comment by marcosgopen** [comment]
> I need to be able to test your PR directly not your own branch since I am providing a review, here's what I did:
> 
> .git/config entry for pulling your PR [remote "upstream"] url = ssh://[git@github.com](mailto:git@github.com)/jbosstm/narayana.io.git fetch = +refs/pull/_/head:refs/remotes/pr/_
> 
> $ which hugo /usr/bin/hugo # I also tried it with /var/lib/snapd/snap/bin/hugo
> 
> git fetch git co pr/63 hugo -e development hugo serve
> 
> When I load http://localhost:1313 in my browser hugo genereates an empty page.
> 
> Same behaviour when I use your branch directly.

You need to run "npm install" before "hugo -e development" otherwise node_modules are not downloaded.
I had pushed node_modules to https://github.com/marcosgopen/marcosgopen.github.io by mistake and then I deleted it (this is maybe why my repo was 'working' for you). That folder should not be pushed but built by the user before running hugo.

**Review by mmusgrov — APPROVED** [review]

**Pull request merged**
